# Generated by Django 4.2.3 on 2023-07-16 06:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_alter_song_release_date_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 6, 32, 6, 488785, tzinfo=datetime.timezone.utc)),
        ),
    ]
