# Generated by Django 4.2.3 on 2023-07-16 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_queue_user_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 6, 35, 56, 974086, tzinfo=datetime.timezone.utc)),
        ),
    ]
